blog/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name='blog'

urlpatterns = [
    path('',views.all_blogs,name = "all_blogs"),
    path('<int:blog_id>',views.details, name="details"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from PortfolioHome import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PortfolioHome/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='PortfolioHome/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title + " | " + str(self.id) 

blog/models.py
from django.db import models

class Blog(models.Model):
    image = models.ImageField(blank = True, upload_to='blog/images/')
    title = models.CharField(max_length = 100)
    date = models.DateField(auto_now_add = True)
    description = models.TextField()

    def __str__(self):
        return self.title + " | " + str(self.id) 

PortfolioHome/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'PortfolioHome/home.html', {"projects":projects})

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
# Create your views here.
def all_blogs(request):
    blogs = Blog.objects.order_by('-date')[:5]
    return render(request, 'blog/all_blogs.html', {"blogs":blogs})
def details(request,blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request,'blog/details.html',{"blog":blog})

PortfolioHome/templates/PortfolioHome/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type='text/css' href='{% static "PortfolioHome\home.css" %}'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link rel="icon" type="image/png" href="{% static 'PortfolioHome/LogoCircleZoom.png' %}">
    <title>kr14</title>
  </head>
  <body>

    <!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}">
    <img src="{% static 'PortfolioHome/LogoCircle.png' %}" width="40" height="40" class="d-inline-block align-top" alt="" loading="lazy">
    kr14
  </a>

  <div class='navitems'>
    <a href='{% url "blog:all_blogs" %}' class='btn btn-primary'>Blog</a>
  </div>
</nav>



    {% block content %}




    {% endblock %}

  </body>
</html>

PortfolioHome/templates/PortfolioHome/home.html
{% extends 'PortfolioHome/base.html' %}
{% block content %}
<div class='containers'>
<div id='header'>
<div class='intro'>
  <div id="textintro">
    <p id='brand'>kr14</p>
    <p class='quote'>"What separates design from art is that design is meant to be... functional."</p>
    <p class='quote'>"Software always remain softly for End users! But sometimes hardly to developers! "</p>
    </div>
</div>
</div>
<div class='projects'>
    <div class='projecthead'>
      <h3>Projects</h3>
      <hr class='hr'>
    </div>


    <div class="row">
      {% for project in projects %}
      <div class="col-lg-4 col-md-6" id='projectContents'>

        {% if project.url %}
        <a href="{{ project.url }}">
          <img src="{{ project.image.url }}" class="img-fluid mb-2">
        </a>
        {% else %}

        <img src="{{ project.image.url }}" class="img-fluid mb-2">
        {% endif %}
        <h3>{{ project.title }}</h3>
        <p>{{ project.description }}</p>

      </div>
      {% endfor %}
    </div>
</div>

{% endblock %}

blog/templates/blog/all_blogs.html
{% extends 'PortfolioHome/base.html' %}
{% block content %}

<h1>Blogs</h1>
<h3>kr14 has written {{ blogs.count }} blog{{ blogs.count|pluralize }}
{% for blog in blogs %}
<a href='{% url "blog:details" blog.id %}'><h2>{{ blog.title }}</h2></a>
{{ blog.date|date:'M d Y'|upper }}
<br>
  {% if blog.image %}
  <img src='{{ blog.image.url }}'>
  {% endif %}
  <br>
{{ blog.description|truncatechars:250 }}

{% endfor %}
{% endblock %}

blog/templates/blog/details.html
{% extends 'PortfolioHome/base.html' %}
{% block content %}

<h1>{{ blog.title }}</h1>
<h3>{{ blog.date |date:'F jS Y' }}</h3>
{% if blog.image %}
<img src='{{ blog.image.url }}'>
{% endif %}
<br>
{{ blog.description|safe }}
{% endblock %}